#Maximum search radius in blocks for /locate biome command.
#The vanilla value is 6400.
#It is not recommended to change the value unless you want to test something or have some issue.
# Default: 6400
# Range: 1600 ~ 12800
biomeSearchRadius = 6400
#When a merchant's treasure map offer ends up not finding a feature location,
#remove the offer instead of marking it out of stock.
removeMerchantInvalidMapOffer = false

["Feature Toggles"]
	#If true, enables asynchronous locating of structures for dolphin treasures.
	dolphinTreasureEnabled = true
	#If true, enables asynchronous locating of structures when Eyes Of Ender are thrown.
	eyeOfEnderEnabled = true
	#If true, enables asynchronous locating of structures for exploration maps found in chests.
	explorationMapEnabled = true
	#If true, enables asynchronous locating of structures for the locate command.
	locateCommandEnabled = true
	#If true, enables asynchronous locating of biomes for the locate command.
	locateBiomeCommandEnabled = true
	#If true, enables asynchronous locating of structures for villager trades.
	villagerTradeEnabled = true
