# If enabled, allows players to access the backpack of another player by interacting
# with the visible backpack on their back.
# Valid values: true, false
enabledPickpocketing = true
# The maximum reach distance of a player to interact with another player's backpack.
# Valid range: 0 to 4 (inclusive)
maxReachDistance = 2.0
# The maximum angle at which another player's backpack can be accessed.
# Think of this as how directly behind the backpack the player needs to be
# in order to pickpocket. A smaller range prevents the player from accessing
# the backpack from the side.
# Valid range: 0 to 90 (inclusive)
maxAngleRange = 80.0
