#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

		[types.stone_type.natures_spirit]
			white_kaolin = true
			light_gray_kaolin = true
			gray_kaolin = true
			black_kaolin = true
			brown_kaolin = true
			red_kaolin = true
			orange_kaolin = true
			yellow_kaolin = true
			lime_kaolin = true
			green_kaolin = true
			cyan_kaolin = true
			light_blue_kaolin = true
			blue_kaolin = true
			purple_kaolin = true
			magenta_kaolin = true
			pink_kaolin = true
			pink_sandstone = true
			white_chalk = false
			light_gray_chalk = false
			gray_chalk = false
			black_chalk = false
			brown_chalk = false
			red_chalk = false
			orange_chalk = false
			yellow_chalk = false
			lime_chalk = false
			green_chalk = false
			cyan_chalk = false
			light_blue_chalk = false
			blue_chalk = false
			purple_chalk = false
			magenta_chalk = false
			pink_chalk = false
			bleached_chalk = false
			travertine = true
			chert = true
			kaolin = true

		[types.stone_type.galosphere]
			pink_salt = true
			rose_pink_salt = true
			pastel_pink_salt = true

		[types.stone_type.atmospheric]
			ivory_travertine = false
			peach_travertine = false
			persimmon_travertine = false
			saffron_travertine = false
			dolerite = true

		[types.stone_type.arts_and_crafts]
			white_chalk = true
			gypsum = true
			soapstone = true

		[types.stone_type.create]
			limestone = true
			asurine = true
			crimsite = true
			ochrum = true
			veridium = true
			scoria = true
			scorchia = true

		[types.stone_type.bountifulfares]
			feldspar = true

		[types.stone_type.darkerdepths]
			aridrock = true
			duskrock = true
			darkslate = true
			grimestone = true

		[types.stone_type.pastel]
			blackslag = true
			preservation_stone = true

		[types.stone_type.enderscape]
			mirestone = true
			veradite = true
			kurodite = true

		[types.stone_type.oreganized]
			glance = true

		[types.cake.bountifulfares]
			coconut_cake = true
			cocoa_cake = true
			sponge_cake = true

		[types.cake.natures_spirit]
			cheese_block = true

		[types.cake.dungeonsdelight]
			monster_cake = true

		[types.cake.neapolitan]
			vanilla_cake = true
			chocolate_cake = true
			strawberry_cake = true
			banana_cake = true
			mint_cake = true
			adzuki_cake = true

		[types.wood_type.dungeonsdelight]
			wormwood = true

		[types.wood_type.darkerdepths]
			petrified = true

		[types.wood_type.mynethersdelight]
			powdery = true

		[types.wood_type.gardens_of_the_dead]
			whistlecane = true
			soulblight = true

		[types.wood_type.pastel]
			black = true
			blue = true
			brown = true
			cyan = true
			gray = true
			green = true
			light_blue = true
			light_gray = true
			lime = true
			magenta = true
			orange = true
			pink = true
			purple = true
			red = true
			white = true
			yellow = true
			weeping_gala = true

		[types.wood_type.bountifulfares]
			hoary = true
			walnut = true

		[types.wood_type.arts_and_crafts]
			cork = true

		[types.wood_type.natures_spirit]
			redwood = true
			sugi = true
			wisteria = true
			fir = true
			willow = true
			aspen = true
			maple = false
			cypress = true
			olive = true
			joshua = true
			ghaf = true
			palo_verde = true
			coconut = true
			cedar = true
			larch = true
			mahogany = true
			saxaul = true

		[types.wood_type.environmental]
			willow = false
			pine = true
			plum = true
			wisteria = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.autumnity]
			maple = true

		[types.wood_type.enderscape]
			veiled = true
			celestial = true
			murublight = true

		[types.wood_type.atmospheric]
			rosewood = true
			morado = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true

		[types.wood_type.malum]
			runewood = true
			soulwood = true

		[types.leaves_type.pastel]
			weeping_gala = true
			nephrite_blossom = true
			spirit_sallow = true
			black = true
			blue = true
			brown = true
			cyan = true
			gray = true
			green = true
			light_blue = true
			light_gray = true
			lime = true
			magenta = true
			orange = true
			pink = true
			purple = true
			red = true
			white = true
			yellow = true

		[types.leaves_type.bountifulfares]
			apple = true
			flowering_apple = true
			orange = true
			flowering_orange = true
			lemon = true
			flowering_lemon = true
			plum = true
			flowering_plum = true
			hoary = true
			walnut = true
			golden_apple = true
			flowering_golden_apple = true

		[types.leaves_type.galosphere]
			opal = true

		[types.leaves_type.arts_and_crafts]
			cork = true

		[types.leaves_type.natures_spirit]
			frosty_redwood = true
			redwood = true
			sugi = true
			wisteria = true
			white_wisteria = true
			part_white_wisteria = false
			blue_wisteria = true
			part_blue_wisteria = false
			pink_wisteria = true
			part_pink_wisteria = false
			purple_wisteria = true
			part_purple_wisteria = false
			frosty_fir = true
			fir = true
			willow = true
			aspen = true
			yellow_aspen = true
			red_maple = true
			orange_maple = true
			yellow_maple = true
			cypress = true
			olive = true
			joshua = true
			ghaf = true
			palo_verde = true
			coconut = true
			cedar = true
			larch = true
			mahogany = true
			saxaul = true

		[types.leaves_type.environmental]
			hibiscus = true
			willow = false
			pine = true
			plum = true
			cheerful_plum = true
			moody_plum = true
			wisteria = true
			pink_wisteria = true
			blue_wisteria = true
			purple_wisteria = true
			white_wisteria = true

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.autumnity]
			maple = true
			yellow_maple = false
			orange_maple = false
			red_maple = false

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			aspen = true
			green_aspen = true
			laurel = true
			dry_laurel = true
			kousa = true
			currant = true
			grimwood = true

		[types.leaves_type.malum]
			runewood = true
			azure_runewood = true
			soulwood = true

#Disables specific entries
[entries]

		[entries.stone_type.create]
			small_brick_wall = true
			cut_wall = true
			small_bricks = true
			cut_brick_slab = true
			polished_cut_slab = true
			small_brick_stairs = true
			cut_bricks = true
			cut = true
			polished_cut = true
			small_brick_slab = true
			layered = true
			polished_cut_stairs = true
			cut_brick_wall = true
			pillar = true
			cut_stairs = true
			cut_brick_stairs = true
			polished_cut_wall = true
			cut_slab = true

		[entries.wood_type.woodworks]
			bookshelf = true
			chiseled_bookshelf = true
			trapped_chest = true
			boards = true
			chest = true
			ladder = true
			beehive = true

		[entries.wood_type.another_furniture]
			table = true
			flower_box = true
			shelf = true
			drawer = true
			shutter = true
			bench = true
			chair = true

		[entries.wood_type.backpacked]
			backpack_shelf = true

		[entries.wood_type.decorative_blocks]
			beam = true
			support = false
			seat = false
			palisade = false

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.bountifulfares]
			trellis = true
			pickets = true

		[entries.leaves_type.woodworks]
			leaf_pile = true
