[client]
	purse = true
	# Default: 0
	# Range: 0 ~ 1000
	creativePurseX = 0
	# Default: 0
	# Range: 0 ~ 2000
	creativePurseY = 0
	# Default: 0
	# Range: 0 ~ 1000
	survivalPurseX = 0
	# Default: 0
	# Range: 0 ~ 2000
	survivalPurseY = 0
	# Default: 0
	# Range: 0 ~ 1000
	merchantPurseX = 0
	# Default: 0
	# Range: 0 ~ 2000
	merchantPurseY = 0
